library/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path
from libraryapp.models import *

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('libraryapp.urls')),
]

libraryapp/urls.py
from django.conf.urls import url
from django.conf.urls import url, include
from django.urls import path
from .views import *

app_name = "libraryapp"

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^books$', book_list, name='books'),
    url(r'^book/form$', book_form, name='book_form'),
    path('books/<int:book_id>/', book_details, name='book'),
    url(r'^books/(?P<book_id>[0-9]+)/form$', book_edit_form, name='book_edit_form'),
    url(r'^librarians$', list_librarians, name='librarians'),
    url(r'accounts/', include('django.contrib.auth.urls')),
    url(r'^logout/$', logout_user, name='logout'),
    url(r'^libraries$', library_list, name='libraries'),
    url(r'^library/form$', library_form, name='library_form'),
    path('libraries/<int:library_id>', library_details, name='library'),
]

libraryapp/models/book.py
from django.db import models
from django.urls import reverse
from .library import Library
from .librarian import Librarian

class Book(models.Model):

    title = models.CharField(max_length=100)
    isbn = models.CharField(max_length=50)
    author = models.CharField(max_length=50)
    published_year = models.IntegerField()
    location = models.ForeignKey(Library, on_delete=models.CASCADE)
    librarian = models.ForeignKey(Librarian, on_delete=models.CASCADE)

    class Meta:
        verbose_name = ("book")
        verbose_name_plural = ("books")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("book_detail", kwargs={"pk": self.pk})

libraryapp/models/librarian.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from .library import Library


class Librarian(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    location = models.ForeignKey(
        Library, related_name="librarians",
        null=True, # Makes column nullable in DB
        blank=True, # Allows blank value on objects
        on_delete=models.CASCADE)


# These receiver hooks allow you to continue to
# work with the `User` class in your Python code.


# Every time a `User` is created, a matching `Librarian`
# object will be created and attached as a one-to-one
# property
@receiver(post_save, sender=User)
def create_librarian(sender, instance, created, **kwargs):
    if created:
        Librarian.objects.create(user=instance)

# Every time a `User` is saved, its matching `Librarian`
# object will be saved.
@receiver(post_save, sender=User)
def save_librarian(sender, instance, **kwargs):
    instance.librarian.save()

libraryapp/models/library.py
from django.db import models
from django.urls import reverse

class Library(models.Model):

    title = models.CharField(max_length=100)
    address = models.CharField(max_length=100)

    class Meta:
        verbose_name = ("library")
        verbose_name_plural = ("libraries")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("library_detail", kwargs={"pk": self.pk})

libraryapp/models/modelfactory.py
import sqlite3

# Higher order function to create instances of models
# when performing single table queries
def model_factory(model_type):
    def create(cursor, row):
        instance = model_type()
        smart_row = sqlite3.Row(cursor, row)
        for col in smart_row.keys():
            setattr(instance, col, smart_row[col])
        return instance
    return create

libraryapp/views/connection.py
class Connection:
    db_path = "/Users/alexr_ku9a8gr/Workspace/python/library/db.sqlite3"

libraryapp/views/home.py
from django.shortcuts import render

def home(request):
    if request.method == 'GET':
        template = 'home.html'
        context = {}

        return render(request, template, context)

libraryapp/templates/books/details.html
{% extends 'shared/base.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Library</title>
</head>

<body>
    {% block content %}
    <section id="book-details">
        <h1>{{ book.title }}</h1>
        <h2>By {{ book.author }}</h2>

        <div>Published in {{ book.published_year }}</div>
        <div>ISBN: {{ book.isbn }}</div>
        <div>Located in the {{ book.location.title }}</div>
        <div>Registered by {{ book.librarian.first_name }} {{ book.librarian.last_name }}</div>
    </section>

    <section id="book-actions" style="display:flex;">
        <form action="{% url 'libraryapp:book' book.id %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="actual_method" value="DELETE">
            <button>Delete</button>
        </form>

        <form action="{% url 'libraryapp:book_edit_form' book.id %}" method="GET">
            {% csrf_token %}
            <button>Edit</button>
        </form>
    </section>
    {% endblock %}
</body>

</html>

libraryapp/templates/books/form.html
{% extends 'shared/base.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Library</title>
</head>

<body>


  {% block content %}

    <h1>Inventory Book</h1>

    {% if book.id is not None %}
        <form action="{% url 'libraryapp:book' book.id %}" method="post">
    {% else %}
        <form action="{% url 'libraryapp:books' %}" method="post">
    {% endif %}
        {% csrf_token %}
        <fieldset>
            <label for="title">Title: </label>
            <input id="title" type="text" name="title" value="{{ book.title }}">
        </fieldset>
        <fieldset>
            <label for="author">Author: </label>
            <input id="author" type="text" name="author" value="{{ book.author }}">
        </fieldset>
        <fieldset>
            <label for="published_year">Year of publication: </label>
            <input id="published_year" type="number" name="published_year" value="{{ book.published_year }}">
        </fieldset>
        <fieldset>
            <label for="isbn">ISBN: </label>
            <input id="isbn" type="text" name="isbn" value="{{ book.isbn }}">
        </fieldset>
        <fieldset>
            <label for="location">Library: </label>
            <select id="location" type="text" name="location">
                {% for library in all_libraries %}
                <option {% if library.id == book.location_id %}selected{% endif %} value="{{ library.id }}">
                    {{ library.title }}</option>
                {% endfor %}
            </select>
        </fieldset>

        {% if book.id is not None %}
            <input type="hidden" name="actual_method" value="PUT">
            <input type="submit" value="Update" />
        {% else %}
            <input type="submit" value="Create" />
        {% endif %}

    </form>

  {% endblock %}

</body>

</html>

libraryapp/templates/books/list.html
{% extends 'shared/base.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
  {% block content %}
    <h1>Books</h1>
    <a href="{% url 'libraryapp:book_form' %}">Add Book to Inventory</a>
    <ol>
    {% for book in all_books %}
        <li>
          <a href="{% url 'libraryapp:book' book.id %}"> {{ book.title }} </a>
          by {{book.author}} published in {{book.published_year}}
        </li>
    {% endfor %}
    </ol>
    {% endblock %}
  </body>
</html>

libraryapp/templates/home.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Nashville Library Management System</title>
</head>

<body>

    <h1>Welcome to the Nashville Library Management System</h1>

</body>

</html>

libraryapp/templates/librarians/list.html
{% extends 'shared/base.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    {% block content %}
    <h1>Librarians</h1>

    <ol>
    {% for librarian in all_librarians %}
        <li>{{ librarian.first_name }} {{ librarian.last_name }}</li>
    {% endfor %}
    </ol>
    {% endblock %}
  </body>
</html>

libraryapp/templates/libraries/details.html
{% extends 'shared/base.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
  {% block content %}
    <h1>{{ library.title }}</h1>
    <h2>Address: {{ library.address }}</h2>
  {% endblock %}
  </body>
</html>

libraryapp/templates/libraries/form.html
{% extends 'shared/base.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Bangazon</title>
  </head>
  <body>
    {% block content %}
    <h1>New Library</h1>


    <form action="{% url 'libraryapp:libraries' %}" method="post">
      {% csrf_token %}
      <fieldset>
          <label for="title">Library Name: </label>
          <input id="title" type="text" name="title">
      </fieldset>
      <fieldset>
          <label for="address">Library Address: </label>
          <input id="address" type="text" name="address">
      </fieldset>

      <input type="submit" value="Add It" />
    </form>
    {% endblock %}
  </body>
</html>

libraryapp/templates/libraries/list.html
{% extends 'shared/base.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Libraries</title>
  </head>
  <body>
  {% block content %}
    <h1>Libraries</h1>

    <a href="{% url 'libraryapp:library_form' %}">Add Library</a>

    <ol>
    {% for library in all_libraries %}
        <li>
            <a href="{% url 'libraryapp:library' library.id %}">
                {{ library.title }}
            </a>
            ({{ library.address }})
            <ul>
            {% for book in library.books %}
                <li>{{ book.title }}</li>
            {% endfor %}
            </ul>
        </li>
    {% endfor %}
    </ol>
{% endblock %}
  </body>
</html>

libraryapp/templates/shared/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Library</title>

    <style>
        .navList {
            list-style-type: none;
            display: flex;
            border: 1px solid lightgray;
            padding: 1em;
        }

        .navList__route {
            margin: 0 0.5em;
        }
    </style>
</head>

<body>

    <nav id="site-nav">
        <ol class="navList">
            <li class="navList__route"><a href="{% url 'libraryapp:libraries' %}">Libraries</a></li>
            <li class="navList__route"><a href="{% url 'libraryapp:books' %}">Books</a></li>
            <li class="navList__route"><a href="{% url 'libraryapp:librarians' %}">Librarians</a></li>
        </ol>
    </nav>

    {% block content %}
    {% endblock %}

</body>

</html>